#! /bin/sh # (there is really no reason to waste 5MB ram to load bash for a simple cp, always use sh if possible)

# put target dir name into a variable to make everything shorter and more readable
TARGET="$SNAP_DATA/xwiki-platform-distribution-jetty-hsqldb-13.10.8"

# make sure the dir we want to copy to is actually existing
[ -d $TARGET ] || mkdir -p $TARGET

# copy the script only if it does not yet exist
if [ ! -e $TARGET/stop_xwiki.sh ]; then
  cp $SNAP/xwiki-platform-distribution-jetty-hsqldb-13.10.8/stop_xwiki.sh $TARGET/
fi
