name: xwiki # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '13.10.8' # just for humans, typically '1.2+git' or '1.3.2'
summary:  XWiki 
description: XWiki is a free wiki software platform written in Java with a design emphasis
 on extensibility.
 .
 XWiki is an easily installed wiki and collaboration platform with features such as
 WYSIWYG editing, OpenOffice based document import/export, semantic annotations
 and tagging, and advanced permissions management.
 .
 XWiki is designed to help teams collaborate more efficiently. It
  runs in a Java servlet container such as Tomcat.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode
parts:
  xwiki:
    plugin: dump
    source: https://nexus.xwiki.org/nexus/content/groups/public/org/xwiki/platform/xwiki-platform-distribution-jetty-hsqldb/13.10.8/xwiki-platform-distribution-jetty-hsqldb-13.10.8.zip
    source-type: zip
    
    override-build: |
      snapcraftctl build
      mv xwiki-platform-distribution-jetty-hsqldb-13.10.8/* .
      rm -r xwiki-platform-distribution-jetty-hsqldb-13.10.8
      chmod u+x start_xwiki.sh
      chmod u+x stop_xwiki.sh
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs   
apps:
  setup:
   command: wrapper
   plugs: [home,network,network-bind]
  start:
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
    command: xwiki-platform-distribution-jetty-hsqldb-13.10.8/start_xwiki.sh
    plugs: [home,network,network-bind]

  stop:
    command: xwiki-platform-distribution-jetty-hsqldb-13.10.8/stop_xwiki.sh
    plugs: [home,network,network-bind]
    
