#! /bin/sh 

# put target dir name into a variable to make everything shorter and more readable
TARGET="$SNAP_DATA/"

# make sure the dir we want to copy to is actually existing
[ -d $TARGET ] || mkdir -p $TARGET

# copy the script only if it does not yet exist
if [ ! -e $TARGET/stop_xwiki.sh ]; then
  cp -r $SNAP/xwiki-platform-distribution-jetty-hsqldb-14.7/* $TARGET/
fi
